### PR TITLE
feat: make `.git` in repo url optional

### PR DESCRIPTION
**Pull request by tanishqmanuja**
I like to copy URL directly from the omnibox of browser reference: #100

Very small PR, but this really hinders my workflow. If merged I wouldn't have to manage my own fork :)

### CODE REVIEW

**Review by joshmedeski — CHANGES_REQUESTED** [review]
I got this error when trying to run it on my machine:
```
t --repo https://github.com/joshmedeski/t-smart-tmux-session-manager
/Users/joshmedeski/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t: line 139: syntax error in conditional expression: unexpected token `)'
/Users/joshmedeski/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t: line 139: syntax error near `\/([^\/]+)\(.git)?'
/Users/joshmedeski/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t: line 139: `         if [[ $REPO_URL =~ \/([^\/]+)\(.git)?$ ]]; then'
```

Looks like the regular expression is invalid.

**Comment by joshmedeski** [comment]
Feel free to fork it (for now) since I'm currently working on a rewrite in GoLang! [Check it out here](https://github.com/joshmedeski/sesh)

**Review by joshmedeski — APPROVED** [review]
It's working, thanks!

**Comment by tanishqmanuja** [comment]
It's not working as expected. So I drafted it xP ... will mess the folder naming if URL contains '.git' at the end

**Pull request merged**
