### PR TITLE
feat: add prompt override when no tmux is running

### PR DESCRIPTION
**Pull request by vitorf7**
Hi @joshmedeski I thought this could be a good addition. However, please feel free to dismiss it if this is not something you might want the package to do.

### CODE REVIEW

**Comment by joshmedeski** [comment]
Interesting. What is the use case here? Do you find it especially useful?

**Comment by vitorf7** [comment]
@joshmedeski yeah it was definitely more of a useful in 1 of 2 scenarios:
1. Consistency of prompt whether or not a tmux server is running
2. Still have 2 different prompts but being able to override the default one and have a Nerd Font prompt rather than the default `>`

**Comment by vitorf7** [comment]
@joshmedeski no problems at all. Let me know if I can help in anything. I'm not a bash guru but this is the least I could do after finding you on YouTube and literally doing an overhaul of my Dev workflow based on your videos which has been massively helpful. Thank you so much.

**Comment by joshmedeski** [comment]
You're welcome, happy to help!

**Pull request closed without merging**
