### PR TITLE
feat: custom border label

### PR DESCRIPTION
**Pull request by erdivartanovich**
Hi there,
First of all, Thanks for this project, It truly helped me in my daily workflow.
I've come across a feature that I believe would greatly enhance its flexibility. Currently, in the Tmux popup, there's no easy way to customize the border label. 
With this PR, I'm proposing to add a feature to allow users to customize the border label in the Tmux popup. 

Thank you.

### CODE REVIEW

**Comment by joshmedeski** [comment]
Hey @erdivartanovich, glad you like it!

I'm open for this change. Would you want this to be switched to a shell variable instead of a tmux option? Otherwise this feature won't work when tmux isn't running.

This is something I've come to realize as we add more features.

**Comment by erdivartanovich** [comment]
Ah, now I realize in the initial call of `t` (serverless/detach) that will call the native `fzf` binary, the border label will not shown, as it seems this is the default behaviour of `fzf`. This is different with `fzf-tmux`  because in its script the `fzf` is called with --border option, [see this line](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux#L190C50-L190C50).
So, I updated this PR to use env var instead of tmux option, and also add fix to make sure border-label always shown in serverless and detach mode as well.

**Comment by erdivartanovich** [comment]
> Thanks! I tested this and it's working well for me.

Wonderful! Anyway, I wonder if is it possible for you to add `hactoberfest-accepted` label to this PR?
I want to participate in [HACTOBERFES](https://hacktoberfest.com/participation/#pr-mr-details)

**Comment by joshmedeski** [comment]
Yes, thanks for contributing!

**Comment by erdivartanovich** [comment]
> Yes, thanks for contributing!

Sorry typo correction, the label should be `hacktoberfest-accepted`, 
thank you @joshmedeski

**Pull request merged**
