### PR TITLE
feat: show set binding on help command

### LINKED ISSUE #34: Update binding on help command
As a user, if I change the default binding for the `t` script, I want the new binding to be reflect in the help command.

### PR DESCRIPTION
**Pull request by TheSast**
Closes #34 
Depends on #35 (will become non-draft if #35 is merged, will close if #35 is closed)

### CODE REVIEW

**Comment by joshmedeski** [comment]
I'll get to this next week, thanks for the hard work!

**Comment by TheSast** [comment]
Currently the "popup while in tmux" section is always shown.
Should it be hidden if it is not called inside tmux (detached)?
Should it be hidden if tmux is not running (serverless)?
Should it be always shown, and attempt to show the correct keymap by launching a tmux session and killing it if tmux was not running (serverless)? or should it fall back to the default binding?

**Comment by joshmedeski** [comment]
What do you think? Perhaps it should just be hidden if tmux is not running.

Maybe state "start tmux to see bindings"?

If we can decide I'm willing to merge it today.

**Comment by TheSast** [comment]
I think the first option may be best: hiding unless called inside tmux.

**Comment by TheSast** [comment]
Should be ready now 👍

**Review by joshmedeski — APPROVED** [review]
This is helpful, thanks!

**Pull request merged**
